In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.datasets import load_boston, load_iris

from sklearn.linear_model import Ridge,Lasso,ElasticNet, LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import make_pipeline
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

from sklearn.neural_network import MLPRegressor
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score

import mglearn
import matplotlib.pyplot as plt
import matplotlib
matplotlib.rcParams['font.family']='Malgun Gothic'
matplotlib.rcParams['axes.unicode_minus'] = False
plt.rcParams['figure.facecolor']='white'
plt.rcParams['figure.figsize']=12.8,10.8
import warnings
warnings.simplefilter('ignore')

In [2]:
train_df=pd.read_excel('data4/hyundaiCar.xlsx',sheet_name='train')
test_df=pd.read_excel('data4/hyundaiCar.xlsx',sheet_name='test')

In [ ]:
x_train=train_df.iloc[:,1:]

In [ ]:
y_train=train_df['가격']

In [ ]:
x_train

In [ ]:
y_train

In [ ]:
x_test=test_df.iloc[:,1:]

In [ ]:
y_test=test_df['가격']

### 문자열 encoding
#### label encoding
#### onehot encoding

In [3]:
from sklearn.preprocessing import OneHotEncoder, LabelEncoder

In [ ]:
x_train ['종류']

### Label Encoder

In [ ]:
lbl= LabelEncoder()
x_trainLabel=lbl.fit_transform(x_train['종류'])

In [ ]:
x_trainLabel

In [ ]:
lbl.classes_

In [ ]:
lbl.classes_[2]

In [ ]:
lbl.transform(['소형'])

### onehotEncoder (0과 1로 구성)

In [ ]:
oneH=OneHotEncoder()
x_trainOne= oneH.fit_transform(x_train['종류'].values.reshape(-1,1))
x_trainOne

In [ ]:
type(x_trainOne)

In [ ]:
x_trainOne.toarray()

In [ ]:
oneH.categories_

In [ ]:
pㅊ

In [ ]:
pd.get_dummies(x_train)

In [ ]:
pd.get_dummies(x_train,columns=['연료','변속기'])

In [ ]:
x_train['종류'].replace(['대형','중형','준중형','소형'],[0,1,2,3])

## 연습문제
### 라벨인코딩을 이용하여

2015 |중형| 12.3| 204| 27| 가솔린 |0 |1591 |1300| 자동 |
자동차 가격 예측하시오

In [5]:
x_train = train_df.iloc[:,1:]
y_train = train_df['가격']

x_test = test_df.iloc[:,1:]
y_test = test_df['가격']

In [6]:
x_train

      년식   종류    연비   마력    토크   연료  하이브리드   배기량    중량 변속기
0   2015  준중형  11.8  172  21.0  가솔린      0  1999  1300  자동
1   2015  준중형  12.3  204  27.0  가솔린      0  1591  1300  자동
2   2015   소형  15.0  100  13.6  가솔린      0  1368  1035  수동
3   2014   소형  14.0  140  17.0  가솔린      0  1591  1090  자동
4   2015   대형   9.6  175  46.0   디젤      0  2497  1990  자동
..   ...  ...   ...  ...   ...  ...    ...   ...   ...  ..
66  2015   중형   8.5  290  34.8  가솔린      0  3342  1901  자동
67  2012   소형  13.3  108  13.9  가솔린      0  1396  1040  자동
68  2015  준중형  12.8  186  41.0   디젤      0  1995  1665  자동
69  2015   중형  17.7  156  19.3  가솔린      1  1999  1585  자동
70  2015   대형  13.8  202  45.0   디젤      0  2199  1691  자동

[71 rows x 10 columns]

In [7]:
x_test

      년식   종류    연비   마력    토크   연료  하이브리드   배기량    중량 변속기
0   2015   대형   6.8  159  23.0  LPG      0  2359  1935  수동
1   2012   소형  13.3  108  13.9  가솔린      0  1396  1035  자동
2   2015   중형  14.4  184  41.0   디젤      0  1995  1792  자동
3   2015   대형  10.9  175  46.0   디젤      0  2497  2210  수동
4   2015   대형   6.4  159  23.0  LPG      0  2359  1935  자동
5   2015   소형  18.0  136  30.6   디젤      0  1582  1160  자동
6   2015  준중형  13.9  184  41.0   디젤      0  1995  1611  수동
7   2015   대형   8.9  133  26.5   디젤      0  2497  1696  수동
8   2015  준중형  12.5  184  41.0   디젤      0  1995  1611  자동
9   2015  준중형  12.8  215  21.3  가솔린      0  1999  1216  수동
10  2015   중형  11.6  168  20.5  가솔린      0  1999  1460  자동
11  2015   중형   8.9  290  34.8  가솔린      0  3342  1832  자동
12  2015   소형  18.0  136  30.6   디젤      0  1582  1190  자동
13  2015  준중형  16.2  128  28.5   디젤      0  1582  1305  자동
14  2015   대형   8.6  282  35.4  가솔린      0  3342  1970  자동
15  2015   소형  19.0  136  30.6   디젤      0  1582  1190  수동
16  2015  준중형  14.4  184  41.0   디젤      0  1995  1548  수동
17  2015   소형  14.1  100  13.6  가솔린      0  1368  1035  자동
18  2014   소형  14.1  100  13.6  가솔린      0  1368  1035  자동
19  2015  준중형  12.4  204  27.0  가솔린      0  1591  1300  수동
20  2014   소형  15.0  100  13.6  가솔린      0  1368  1035  수동
21  2015  준중형  13.0  140  17.0  가솔린      0  1591  1225  수동
22  2015   대형   7.4  416  52.0  가솔린      0  5038  2145  자동
23  2015  준중형  11.8  172  21.0  가솔린      0  1999  1325  자동
24  2015  준중형  12.4  215  21.3  가솔린      0  1999  1216  자동
25  2015  준중형  14.0  140  17.0  가솔린      0  1591  1210  자동
26  2015   대형   8.9  334  40.3  가솔린      0  3778  1915  자동
27  2015   대형   8.7  175  46.0   디젤      0  2497  2383  수동
28  2015   대형   9.6  175  46.0   디젤      0  2497  1990  자동
29  2010   소형  13.0   95  12.7  가솔린      0  1399  1046  자동
30  2015   중형  14.8  200  43.0   디젤      0  2199  1760  수동

In [8]:
 lbl= LabelEncoder()

In [9]:
def encode_features(x_train) :
    features = ['종류', '연료', '변속기']
    for feature in features:
        lbl= LabelEncoder()
        lbl = lbl.fit(x_train[feature])
        x_train[feature] = lbl.transform(x_train[feature])
        
    return x_train

encode_features(x_train)

      년식  종류    연비   마력    토크  연료  하이브리드   배기량    중량  변속기
0   2015   2  11.8  172  21.0   1      0  1999  1300    1
1   2015   2  12.3  204  27.0   1      0  1591  1300    1
2   2015   1  15.0  100  13.6   1      0  1368  1035    0
3   2014   1  14.0  140  17.0   1      0  1591  1090    1
4   2015   0   9.6  175  46.0   2      0  2497  1990    1
..   ...  ..   ...  ...   ...  ..    ...   ...   ...  ...
66  2015   3   8.5  290  34.8   1      0  3342  1901    1
67  2012   1  13.3  108  13.9   1      0  1396  1040    1
68  2015   2  12.8  186  41.0   2      0  1995  1665    1
69  2015   3  17.7  156  19.3   1      1  1999  1585    1
70  2015   0  13.8  202  45.0   2      0  2199  1691    1

[71 rows x 10 columns]

In [10]:
encode_features(x_test)

      년식  종류    연비   마력    토크  연료  하이브리드   배기량    중량  변속기
0   2015   0   6.8  159  23.0   0      0  2359  1935    0
1   2012   1  13.3  108  13.9   1      0  1396  1035    1
2   2015   3  14.4  184  41.0   2      0  1995  1792    1
3   2015   0  10.9  175  46.0   2      0  2497  2210    0
4   2015   0   6.4  159  23.0   0      0  2359  1935    1
5   2015   1  18.0  136  30.6   2      0  1582  1160    1
6   2015   2  13.9  184  41.0   2      0  1995  1611    0
7   2015   0   8.9  133  26.5   2      0  2497  1696    0
8   2015   2  12.5  184  41.0   2      0  1995  1611    1
9   2015   2  12.8  215  21.3   1      0  1999  1216    0
10  2015   3  11.6  168  20.5   1      0  1999  1460    1
11  2015   3   8.9  290  34.8   1      0  3342  1832    1
12  2015   1  18.0  136  30.6   2      0  1582  1190    1
13  2015   2  16.2  128  28.5   2      0  1582  1305    1
14  2015   0   8.6  282  35.4   1      0  3342  1970    1
15  2015   1  19.0  136  30.6   2      0  1582  1190    0
16  2015   2  14.4  184  41.0   2      0  1995  1548    0
17  2015   1  14.1  100  13.6   1      0  1368  1035    1
18  2014   1  14.1  100  13.6   1      0  1368  1035    1
19  2015   2  12.4  204  27.0   1      0  1591  1300    0
20  2014   1  15.0  100  13.6   1      0  1368  1035    0
21  2015   2  13.0  140  17.0   1      0  1591  1225    0
22  2015   0   7.4  416  52.0   1      0  5038  2145    1
23  2015   2  11.8  172  21.0   1      0  1999  1325    1
24  2015   2  12.4  215  21.3   1      0  1999  1216    1
25  2015   2  14.0  140  17.0   1      0  1591  1210    1
26  2015   0   8.9  334  40.3   1      0  3778  1915    1
27  2015   0   8.7  175  46.0   2      0  2497  2383    0
28  2015   0   9.6  175  46.0   2      0  2497  1990    1
29  2010   1  13.0   95  12.7   1      0  1399  1046    1
30  2015   3  14.8  200  43.0   2      0  2199  1760    0

In [11]:
modelElastic = Pipeline([ ('scl',StandardScaler()), ('clf', ElasticNet()) ])
param_value = {
    'clf__alpha': [0.001,0.01,1,2,3,4],
    'clf__l1_ratio' : [0.4,0.5,0.6,0.7],
}

In [12]:
gridSearch = GridSearchCV( modelElastic, param_grid= param_value, cv = 10, n_jobs = -1,verbose = 1)
gridSearch.fit(x_train, y_train)

Fitting 10 folds for each of 24 candidates, totalling 240 fits

GridSearchCV(cv=10,
             estimator=Pipeline(steps=[('scl', StandardScaler()),
                                       ('clf', ElasticNet())]),
             n_jobs=-1,
             param_grid={'clf__alpha': [0.001, 0.01, 1, 2, 3, 4],
                         'clf__l1_ratio': [0.4, 0.5, 0.6, 0.7]},
             verbose=1)

In [13]:
print(gridSearch.best_score_)
print(gridSearch.best_params_)

0.5839143306366059
{'clf__alpha': 0.01, 'clf__l1_ratio': 0.4}

In [14]:
result = gridSearch.best_estimator_.predict([[2015, 2 , 12.3,204, 27,1, 0, 1519, 1300, 1]])
print('가격: ', result)

가격:  [1952.23100494]